server:
  port: 8001
  tomcat:
    max-threads: 10
spring:
  application:
    name: mypractice-teacher
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.200:3306/mypractice?characterEncoding=utf-8&useUnicode=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos的服务地址
    sentinel:
      transport:
        port: 8081 #控制台交流的端口 随便指定即可
        dashboard: localhost:8080  #控制台
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:com/suki/teacher/mapper/xml/*.xml
debug: true


logging:
  level:
    root: info

mypractice-oss: #服务生产者
  ribbon:
    MaxAutoRetries: 0 #同一实例最大重试次数，不包括首次调用 默认0
    MaxAutoRetriesNextServer: 1 #重试其他实例的最大重试次数，不包括首次所选的server 默认1
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ConnectTimeout: 10000 #默认1秒
    ReadTimeout: 10000 #默认1秒

feign:
  sentinel:
    enabled: true
